apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: loki-template
message: |-
  The following service(s) have been created in your project: ${LOKI_SERVICE_NAME}.
  For more information about using this template, including OpenShift considerations, contact the rocketchat community.
metadata:
  annotations:
    description: |-
      Loki Template for use in OpenShift 201 lab without persistent storage. 

      WARNING: Any configuration stored will be lost upon pod destruction. ConfigMaps should be used for codified configuration. 
    iconClass: icon-other-unknown
    openshift.io/display-name: loki-openshift201
    openshift.io/documentation-url: https://github.com/bcdevops/devops-platform-workshops
    openshift.io/long-description: This template provides a sample Grafana configuration for lab purposes.
    openshift.io/provider-display-name: BCDevOps
    openshift.io/support-url: https://github.com/bcdevops/
    tags: monitoring,loki
  name: loki-template
objects: 
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${LOKI_SERVICE_NAME}
      chart: loki-0.16.0
      heritage: Tiller
      release: ${LOKI_SERVICE_NAME}
    name: ${LOKI_SERVICE_NAME}
  spec:
    ports:
    - name: http-metrics
      port: 3100
      protocol: TCP
      targetPort: http-metrics
    selector:
      app: ${LOKI_SERVICE_NAME}
      release: ${LOKI_SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${LOKI_SERVICE_NAME}
      chart: loki-0.16.0
      heritage: Tiller
      release: ${LOKI_SERVICE_NAME}
    name: ${LOKI_SERVICE_NAME}-headless
  spec:
    clusterIP: None
    ports:
    - name: http-metrics
      port: 3100
      protocol: TCP
      targetPort: http-metrics
    selector:
      app: ${LOKI_SERVICE_NAME}
      release: ${LOKI_SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    labels:
      app: ${LOKI_SERVICE_NAME}
      chart: loki-0.16.0
      heritage: Tiller
      release: ${LOKI_SERVICE_NAME}
    name: ${LOKI_SERVICE_NAME}
  spec:
    podManagementPolicy: OrderedReady
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: ${LOKI_SERVICE_NAME}
        release: ${LOKI_SERVICE_NAME}
    serviceName: ${LOKI_SERVICE_NAME}-headless
    template:
      metadata:
        annotations:
          checksum/config: 1b39b35c08c66d681d77312a0d32f719bb080208d9e3b55fe0be4146b31ec809
          prometheus.io/port: http-metrics
          prometheus.io/scrape: "true"
        creationTimestamp: null
        labels:
          app: ${LOKI_SERVICE_NAME}
          name: ${LOKI_SERVICE_NAME}
          release: ${LOKI_SERVICE_NAME}
      spec:
        affinity: {}
        containers:
        - args:
          - -config.file=/etc/loki/loki.yaml
          image: grafana/loki:v0.3.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: http-metrics
              scheme: HTTP
            initialDelaySeconds: 45
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: ${LOKI_SERVICE_NAME}
          ports:
          - containerPort: 3100
            name: http-metrics
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: http-metrics
              scheme: HTTP
            initialDelaySeconds: 45
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/loki
            name: config
          - mountPath: /data
            name: storage
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: default
        serviceAccountName: default
        terminationGracePeriodSeconds: 30
        volumes:
        - name: config
          secret:
            defaultMode: 420
            secretName: ${LOKI_SERVICE_NAME}
        - emptyDir: {}
          name: storage
    updateStrategy:
      type: RollingUpdate
parameters:
- description: The name of the Loki app
  displayName: Loki Service Name
  name: LOKI_SERVICE_NAME
  required: true
  value: mtcarto-loki
